<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsNotAsErrors>$(WarningsNotAsErrors);NU1900</WarningsNotAsErrors>
    <AnalysisMode>Recommended</AnalysisMode>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <VersionPrefix>1.1.0</VersionPrefix>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>embedded</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>
